### PR TITLE
Sync your master with Freenet

### PR DESCRIPTION
**Pull request by xor-freenet**
Please hereby fast-forward your branch master to Freenet's master.

### CODE REVIEW

**Comment by ArneBab** [comment]
Looks good. Mostly @override , the rest well-commented. Thank you!

**Comment by xor-freenet** [comment]
Thanks a lot for merging!! Happy to see WoT/FT code flowing again :)
But uhm, I think I failed to explain the git commands properly:

This was not supposed to be merged with a merge commit into the master of Freenet as all of these commits **were** already in Freenet's master.
It was merely intended to remind you that your **own** master was **behind** Freenet's master.
I.e. it wanted to request you to fast-forward your master to Freenet's.

Sorry if this was my fault by not being precise enough in the PR message! :(
I can provide command line merge instructions again for future PRs if you want me to?

By merging this into the Freenet master you created a merge commit which sort of pretends that Freenet's master was behind itself.
See `gitk 38ff5ef050e828c8d231d90fa10b92f4bbbe2df1`.
The commit `aef49aa771c498cd0473188ac9c132c1e7879eb4` in that tree is the unneeded, empty merge commit (notice that the commit message seems wrong, it merged the PR 1 of **your** repo, not of Freenet's).

Unfortunately now the pending PRs cannot be fast-forwarded anymore as fast-forwarding only works if the two repositories did not diverge, but now the merge-commits you introduced are what has diverged. You have them in your repo, I don't have them in mine = diverging.
That's also what caused your other merge commits even though my PRs were supposed to be ff-able.  
(You also ran into unnecessary non-ff merges on WoT, though I don't know the reason there as your repo was in sync.)

This could be resolved in two ways:

1. Force-pushing Freenet's and your master to the last commit of this PR = restoring it to where it was before. Then the PRs after this one could be merged with `--ff-only`.
However under toad force-pushing was discouraged, I don't know the stance of current Freenet OPs.

2. Keeping the unnecessary commits in the history by having me merge them into my repo. However that would please have to wait until all of the existing PRs have been merged by you and I create new PRs, I cannot untangle hundreds of commits now :( Notice that fast-forward won't work until then with this solution.

Make up your mind on how to resolve this, I will accept your decision.
Sorry if my lack of explaining the Git commands has caused this!

**Comment by ArneBab** [comment]
It is intentional to leave an explicit, signed commit which shows that I reviewed this state.

**Comment by xor-freenet** [comment]
@ArneBab 
> It is intentional to leave an explicit, signed commit which shows that I reviewed this state.

Oh I misunderstood your reason then! Sorry!
(And thanks for your patience in reading this long text so soon!)

That's what signed git tags are for! :) We already have them on Freetalk, they're called "reviewed-*".
I would suggest "reviewed-arnebab-YYYY-MM-DD".

If we had everyone who reviewed a certain commit/branch create a merge commit then the history would possibly contain like 4 merge commits for a single branch if we ever achieve to have proper review by at least 3 people.
That's certainly not desirable?

There's also a benefit of less work for you in `--fast-forward`: You're fully outsourcing the git history/branch management to me, you're basically only copying stuff over.

And to be honest I do not wish the years of meticulously keeping the git history clean to become in vain now solely induced by social issues at Freenet.
I am willing to merge back upcoming unnecessary merge commits for all pending PRs given that they're not fast-forwardable anymore (except the one(s) which merely ask you to sync your branches with Freenet, those will ff), but I would be really happy if we could move back to fast-forward afterwards?

Thanks again for reading so much :)

**Pull request merged**
