### PR TITLE
GitHub Actions part 1: Add GHA script by converting Travis CI script into it

### PR DESCRIPTION
**Pull request by xor-freenet**
_Please merge with `--ff-only` into `master`._
_This also contains the commits of the previous PRs to that branch._

---

**EDIT:** For security, before merging this please go to the `Settings` tabs of
the Freenet and your own Freetalk repository and set:
`Actions / Workflow permissions: Read repository contents permission`.
Then click `Save` below that.
In other words: It should not have write-access.
Please confirm by commenting that you did remove the write access.

### CODE REVIEW

**Comment by xor-freenet** [comment]
Please take notice of the "EDIT:" part in the PR message.
(Commenting that because it likely won't email about it.)

**Comment by xor-freenet** [comment]
You missed the "EDIT: For security [...]" part, please process that.

**Comment by ArneBab** [comment]
Both are already set to  "Workflows have read permissions in the repository for the contents scope only."

**Comment by ArneBab** [comment]
(but thank you for the reminder!)

**Pull request merged**
